version: '3'


volumes:
  backend_data: {}
  static: {}

services:
  backend:
    build:
      context: .
      dockerfile: compose/backend/Dockerfile
    command: sh -c "bash /scripts/wait-for-it.sh --host=db --port=5432 &&
                    uvicorn main:app --workers 4 --host 0.0.0.0 --port 8000"
    env_file:
      - .envs
    volumes:
    - static:/static
    - ./lite_b:/app
    - ./utils:/packages/rgs_utils
    depends_on:
      - db

  scrap:
    build:
      context: .
      dockerfile: compose/backend/Dockerfile
    command: sh -c "bash /scripts/wait-for-it.sh --host=db --port=5432 &&
                    python main.py"
    env_file:
      - .envs
    volumes:
    - ./grpc_scrap:/app
    - ./utils:/packages/rgs_utils
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - backend_data:/var/lib/postgresql/data
    env_file:
      - .envs


  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    volumes:
    - static:/static
    ports:
      - 0.0.0.0:8000:8000
    depends_on:
      - backend