# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"j\n\rLaunchUrlData\x12*\n\x06params\x18\x01 \x03(\x0b\x32\x1a.LaunchUrlData.ParamsEntry\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1b\n\x0c\x41uthResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2@\n\x0cScrapService\x12\x30\n\rAuthLaunchUrl\x12\x0e.LaunchUrlData\x1a\r.AuthResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LAUNCHURLDATA_PARAMSENTRY._options = None
  _LAUNCHURLDATA_PARAMSENTRY._serialized_options = b'8\001'
  _LAUNCHURLDATA._serialized_start=18
  _LAUNCHURLDATA._serialized_end=124
  _LAUNCHURLDATA_PARAMSENTRY._serialized_start=79
  _LAUNCHURLDATA_PARAMSENTRY._serialized_end=124
  _AUTHRESPONSE._serialized_start=126
  _AUTHRESPONSE._serialized_end=153
  _SCRAPSERVICE._serialized_start=155
  _SCRAPSERVICE._serialized_end=219
# @@protoc_insertion_point(module_scope)
